source 'https://cdn.cocoapods.org/'

platform :ios, '16.0'
ENV['FLUTTER_ROOT'] = '/usr/local/flutter'
load File.join(__dir__, 'Flutter', 'podhelper.rb')


ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

load File.join(__dir__, 'Flutter', 'podhelper.rb')



flutter_ios_podfile_setup

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_install_all_ios_pods

  # --- Compatibility fixes ---
  pod 'AppAuth', '>= 1.7.4'
  pod 'GoogleSignIn', '~> 8.0'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '16.0'
      config.build_settings['SWIFT_VERSION'] = '5.0'
    end
  end

  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
  end
end
