source 'https://cdn.cocoapods.org/'

platform :ios, '17.0'

use_frameworks!
use_modular_headers!

flutter_application_path = File.expand_path('..', __dir__)
load File.join(flutter_application_path, 'Flutter', 'podhelper.rb')

target 'Runner' do
  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))

  pod 'Firebase/CoreOnly', '10.22.0'
  pod 'FirebaseCrashlytics', '10.22.0'
  pod 'GoogleUtilities', '~> 7.13.3'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '17.0'
      config.build_settings['SWIFT_VERSION'] = '5.0'
    end
  end
end
